# Generated by Django 4.2.17 on 2025-01-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(blank=True, default='No Subject', max_length=255),
        ),
    ]
